# Generated by Django 4.0.4 on 2022-05-31 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.IntegerField(max_length=32, primary_key=True, serialize=False)),
                ('teacher_num', models.CharField(max_length=16)),
                ('teacher_name', models.CharField(max_length=16)),
                ('teacher_age', models.CharField(max_length=16)),
                ('t_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_t', to='UserInfo.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(max_length=32, primary_key=True, serialize=False)),
                ('student_num', models.CharField(max_length=16)),
                ('student_name', models.CharField(max_length=16)),
                ('student_age', models.CharField(max_length=16)),
                ('s_u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_s', to='UserInfo.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='StuCourse',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('t_id', models.IntegerField()),
                ('s_stus', models.ManyToManyField(related_name='c_cours', to='UserInfo.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(max_length=32, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=16)),
                ('c_teas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_cour', to='UserInfo.teacher')),
            ],
        ),
    ]
