# Generated by Django 4.0.4 on 2022-05-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_teacher_student_stucourse_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='c_teas',
        ),
        migrations.AddField(
            model_name='teacher',
            name='ts_cour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='c_teas', to='UserInfo.course'),
            preserve_default=False,
        ),
    ]
