# Generated by Django 4.0.4 on 2022-05-31 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0003_remove_course_c_teas_teacher_ts_cour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='ts_cour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_teas', to='UserInfo.course'),
        ),
    ]
