# Generated by Django 4.0.4 on 2022-05-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0004_alter_teacher_ts_cour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_kind',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
